export { default as Favicon } from "/public/images/favicon.png"
export { default as LogoImage } from "/public/images/logo.svg"
export { default as LogoIcon } from "/public/images/logo_icon.svg"

export { default as IconAppStore } from "/public/images/app-store.svg"
export { default as IconPlayStore } from "/public/images/play-store.svg"

export { default as PhoneIcon } from "/public/images/phone_icon.svg"
export { default as EnvelopeIcon } from "/public/images/envelope_icon.svg"
export { default as QuoteIcon } from "/public/images/quotes.svg"
export { default as PlayIcon } from "/public/images/video_icon.svg"
export { default as FaqIcon } from "/public/images/faq-icon.svg"

export { default as PhotoMainBannerVector } from "/public/images/main_banner_vector2.svg"
// export { default as PhotoMainBanner } from "/public/images/Kia-Car-PNG-HD.png"
export { default as PhotoHelp } from "/public/images/Kia-Car-PNG-HD.png"
export { default as PhotoMainBanner } from "/public/images/pngimg.com---mercedes_PNG80136.png"
export { default as PhotoWork } from "/public/images/Kia-Car-PNG-Photos.png"
export { default as PhotoVector_01 } from "/public/images/vector_01.svg"
export { default as PhotoVector_02 } from "/public/images/vector_02.svg"
export { default as PhotoVector_03 } from "/public/images/vector_03.svg"
export { default as PhotoBrandCoinbase } from "/public/images/brand_coinbase.svg"
export { default as PhotoBrandJohnDeere } from "/public/images/brand_johnDeere.svg"
export { default as PhotoBrandGrandHyatt } from "/public/images/brand_Grand-Hyatt.svg"
export { default as PhotoBrandBlk_google } from "/public/images/brand_blk_google.svg"
export { default as PhotoBrandVisa } from "/public/images/brand_Visa.svg"
export { default as PhotoBrandZoom } from "/public/images/brand_Zoom.webp"

export { default as VectorIconPricing } from "/public/images/pricing.svg"
export { default as VectorIconCompass } from "/public/images/compass.svg"
export { default as VectorIconSolutions } from "/public/images/solutions.svg"

export { default as PhotoUser_01 } from "/public/images/users/01.jpg"
export { default as PhotoUser_02 } from "/public/images/users/02.jpg"
export { default as PhotoUser_03 } from "/public/images/users/03.jpg"
export { default as PhotoUser_04 } from "/public/images/users/04.jpg"
export { default as PhotoUser_05 } from "/public/images/users/05.jpg"
export { default as PhotoUser_06 } from "/public/images/users/06.jpg"
export { default as PhotoUser_07 } from "/public/images/users/07.jpg"
export { default as PhotoUser_08 } from "/public/images/users/08.jpg"
export { default as PhotoUser_09 } from "/public/images/users/09.jpg"
export { default as PhotoUser_10 } from "/public/images/users/10.jpg"

export { default as SocialTwitter } from "/public/images/social-twitter.svg"
export { default as SocialFacebook } from "/public/images/social-facebook.svg"
export { default as SocialLinkedin } from "/public/images/social-linkedin.svg"
export { default as SocialInstagram } from "/public/images/social-instagram.svg"
